//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Nullable<int> postID { get; set; }
        public Nullable<int> writerID { get; set; }
        public int commentID { get; set; }
        public string content { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
