//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class React
    {
        public int postID { get; set; }
        public int userID { get; set; }
        public Nullable<int> typeOfReact { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
